-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2569-10-04 22:14:48 ICT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE affiliation (
    affiliation_id   NUMBER(10) NOT NULL,
    affiliation_name VARCHAR2(255) NOT NULL
);

ALTER TABLE affiliation ADD CONSTRAINT affiliation_pk PRIMARY KEY ( affiliation_id );

CREATE TABLE booking (
    booking_id          NUMBER(10) NOT NULL,
    booking_date        DATE NOT NULL,
    start_time          TIMESTAMP NOT NULL,
    end_time            TIMESTAMP NOT NULL,
    purpose             VARCHAR2(500),
    booking_status      VARCHAR2(50),
    actual_checkin_time TIMESTAMP,
    users_user_id       NUMBER(10) NOT NULL,
    room_room_id        NUMBER(10) NOT NULL,
    staff_staff_id      NUMBER(10),
    created_at          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT current_timestamp NOT NULL,
    updated_at          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT current_timestamp,
    approved_at         TIMESTAMP WITH LOCAL TIME ZONE,
    reject_reason       VARCHAR2(500)
);

CREATE INDEX idx_booking_user ON
    booking (
        users_user_id
    ASC );

CREATE INDEX idx_booking_availability ON
    booking (
        room_room_id
    ASC,
        start_time
    ASC,
        end_time
    ASC );

CREATE INDEX idx_booking_user_history ON
    booking (
        users_user_id
    ASC,
        created_at
    ASC );

CREATE SEQUENCE booking_log_seq START WITH 1 INCREMENT BY 1;

ALTER TABLE booking ADD CONSTRAINT ck_booking_time CHECK ( end_time > start_time );

ALTER TABLE booking
    ADD CONSTRAINT ck_booking_status CHECK ( booking_status IN ( 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'CHECKED_IN',
                                                                 'COMPLETED' ) );

ALTER TABLE booking ADD CONSTRAINT booking_pk PRIMARY KEY ( booking_id );

CREATE TABLE booking_equipment (
    booking_booking_id     NUMBER(10) NOT NULL,
    equipment_equipment_id NUMBER(10) NOT NULL,
    borrowed_qty           NUMBER(5)
);

ALTER TABLE booking_equipment ADD CONSTRAINT ck_be_qty CHECK ( borrowed_qty > 0 );

ALTER TABLE booking_equipment ADD CONSTRAINT booking_equipment_pk PRIMARY KEY ( booking_booking_id,
                                                                                equipment_equipment_id );

CREATE TABLE booking_log (
    booking_log_id     NUMBER(10) NOT NULL,
    action_type        VARCHAR2(100),
    action_time        TIMESTAMP,
    violation_flag     VARCHAR2(10),
    booking_booking_id NUMBER(10),
    users_user_id      NUMBER(10)
);

ALTER TABLE booking_log
    ADD CONSTRAINT booking_log_violation_ck CHECK ( violation_flag IN ( 'YES', 'NO' ) );

ALTER TABLE booking_log ADD CONSTRAINT booking_log_pk PRIMARY KEY ( booking_log_id );

CREATE TABLE booking_participant (
    booking_booking_id   NUMBER(10) NOT NULL,
    users_user_id        NUMBER(10) NOT NULL,
    participation_status VARCHAR2(50)
);

ALTER TABLE booking_participant ADD CONSTRAINT booking_participant_pk PRIMARY KEY ( booking_booking_id,
                                                                                    users_user_id );

CREATE TABLE building (
    building_id   NUMBER(10) NOT NULL,
    building_name VARCHAR2(255) NOT NULL,
    address       VARCHAR2(255)
);

ALTER TABLE building ADD CONSTRAINT building_pk PRIMARY KEY ( building_id );

CREATE TABLE equipment (
    equipment_id       NUMBER(10) NOT NULL,
    equipment_name     VARCHAR2(255) NOT NULL,
    equipment_type     VARCHAR2(100),
    equipment_status   VARCHAR2(50),
    remaining_qty      NUMBER(5),
    created_at         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT current_timestamp,
    updated_at         TIMESTAMP WITH LOCAL TIME ZONE,
    created_by_user_id NUMBER(10),
    is_deleted         NUMBER(1) DEFAULT 0,
    deleted_at         TIMESTAMP WITH LOCAL TIME ZONE
);

ALTER TABLE equipment ADD CONSTRAINT equipment_qty_ck CHECK ( remaining_qty >= 0 );

ALTER TABLE equipment ADD CONSTRAINT equipment_pk PRIMARY KEY ( equipment_id );

CREATE TABLE floor (
    floor_id             NUMBER(10) NOT NULL,
    floor_number         VARCHAR2(50) NOT NULL,
    building_building_id NUMBER(10) NOT NULL
);

ALTER TABLE floor ADD CONSTRAINT floor_pk PRIMARY KEY ( floor_id );

CREATE TABLE holiday (
    holiday_id   NUMBER(10) NOT NULL,
    holiday_date DATE NOT NULL,
    description  VARCHAR2(255)
);

ALTER TABLE holiday ADD CONSTRAINT holiday_pk PRIMARY KEY ( holiday_id );

CREATE TABLE notification (
    notification_id    NUMBER(10) NOT NULL,
    noti_type          VARCHAR2(50),
    content            VARCHAR2(1000),
    recipient_email    VARCHAR2(100),
    send_time          TIMESTAMP,
    booking_booking_id NUMBER(10),
    users_user_id      NUMBER(10) NOT NULL,
    template_code      VARCHAR2(50) NOT NULL,
    params_json        VARCHAR2(1000),
    created_at         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT current_timestamp NOT NULL
);

CREATE SEQUENCE notification_seq START WITH 1 INCREMENT BY 1;

ALTER TABLE notification ADD CONSTRAINT notification_pk PRIMARY KEY ( notification_id );

CREATE TABLE penalty (
    penalty_id         NUMBER(10) NOT NULL,
    penalty_type       VARCHAR2(100),
    start_date         DATE,
    end_date           DATE,
    reason             VARCHAR2(500),
    penalty_status     VARCHAR2(50),
    users_user_id      NUMBER(10) NOT NULL,
    staff_staff_id     NUMBER(10),
    booking_booking_id NUMBER(10),
    created_at         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT current_timestamp NOT NULL,
    updated_at         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT current_timestamp
);

ALTER TABLE penalty ADD CONSTRAINT penalty_date_ck CHECK ( end_date >= start_date );

ALTER TABLE penalty ADD CONSTRAINT penalty_pk PRIMARY KEY ( penalty_id );

CREATE TABLE report (
    report_id      NUMBER(10) NOT NULL,
    report_type    VARCHAR2(100),
    report_date    DATE NOT NULL,
    total_bookings NUMBER(6) NOT NULL,
    user_userid    NUMBER(10),
    total_hours    NUMBER(8, 2) NOT NULL,
    canceled_count NUMBER(6),
    created_at     TIMESTAMP WITH LOCAL TIME ZONE DEFAULT current_timestamp NOT NULL
);

ALTER TABLE report ADD CONSTRAINT report_pk PRIMARY KEY ( report_id );

CREATE TABLE room (
    room_id                NUMBER(10) NOT NULL,
    room_name              VARCHAR2(100) NOT NULL,
    capacity               NUMBER(5),
    room_status            VARCHAR2(50),
    image_url              VARCHAR2(500),
    floor_floor_id         NUMBER(10),
    room_type_room_type_id NUMBER(10),
    is_deleted             NUMBER(1) DEFAULT 0,
    deleted_at             TIMESTAMP WITH LOCAL TIME ZONE
);

ALTER TABLE room ADD CONSTRAINT room_pk PRIMARY KEY ( room_id );

CREATE TABLE room_assignment (
    staff_staff_id NUMBER(10) NOT NULL,
    room_room_id   NUMBER(10) NOT NULL,
    start_date     DATE,
    work_shift     VARCHAR2(50)
);

ALTER TABLE room_assignment ADD CONSTRAINT room_assignment_pk PRIMARY KEY ( staff_staff_id,
                                                                            room_room_id );

CREATE TABLE room_equipment (
    room_room_id           NUMBER(10) NOT NULL,
    equipment_equipment_id NUMBER(10) NOT NULL,
    quantity               NUMBER(5),
    equip_status           VARCHAR2(50)
);

ALTER TABLE room_equipment ADD CONSTRAINT room_equipment_qty_ck CHECK ( quantity > 0 );

ALTER TABLE room_equipment ADD CONSTRAINT room_equipment_pk PRIMARY KEY ( room_room_id,
                                                                          equipment_equipment_id );

CREATE TABLE room_type (
    room_type_id NUMBER(10) NOT NULL,
    type_name    VARCHAR2(100) NOT NULL,
    description  VARCHAR2(500)
);

ALTER TABLE room_type ADD CONSTRAINT room_type_pk PRIMARY KEY ( room_type_id );

CREATE TABLE staff (
    staff_id      NUMBER(10) NOT NULL,
    job_title     VARCHAR2(100),
    start_date    DATE,
    staff_status  VARCHAR2(50),
    users_user_id NUMBER(10)
);

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( staff_id );

ALTER TABLE staff ADD CONSTRAINT staff_users_user_id_un UNIQUE ( users_user_id );

CREATE TABLE users (
    user_id                    NUMBER(10) NOT NULL,
    full_name                  VARCHAR2(255) NOT NULL,
    email                      VARCHAR2(100) NOT NULL,
    phone                      VARCHAR2(20),
    role_level                 VARCHAR2(50),
    account_status             VARCHAR2(50),
    affiliation_affiliation_id NUMBER(10),
    created_at                 TIMESTAMP WITH LOCAL TIME ZONE DEFAULT current_timestamp,
    updated_at                 TIMESTAMP WITH LOCAL TIME ZONE DEFAULT current_timestamp,
    is_deleted                 NUMBER(1) DEFAULT 0 NOT NULL,
    deleted_at                 TIMESTAMP WITH LOCAL TIME ZONE
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( user_id );

ALTER TABLE users ADD CONSTRAINT users_email_un UNIQUE ( email );

ALTER TABLE booking_equipment
    ADD CONSTRAINT booking_equipment_booking_fk FOREIGN KEY ( booking_booking_id )
        REFERENCES booking ( booking_id );

ALTER TABLE booking_equipment
    ADD CONSTRAINT booking_equipment_equipment_fk FOREIGN KEY ( equipment_equipment_id )
        REFERENCES equipment ( equipment_id );

ALTER TABLE booking_log
    ADD CONSTRAINT booking_log_booking_fk FOREIGN KEY ( booking_booking_id )
        REFERENCES booking ( booking_id );

ALTER TABLE booking_log
    ADD CONSTRAINT booking_log_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE booking_participant
    ADD CONSTRAINT booking_participant_booking_fk FOREIGN KEY ( booking_booking_id )
        REFERENCES booking ( booking_id );

ALTER TABLE booking_participant
    ADD CONSTRAINT booking_participant_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_room_fk FOREIGN KEY ( room_room_id )
        REFERENCES room ( room_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_staff_fk FOREIGN KEY ( staff_staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE floor
    ADD CONSTRAINT floor_building_fk FOREIGN KEY ( building_building_id )
        REFERENCES building ( building_id );

ALTER TABLE notification
    ADD CONSTRAINT notification_booking_fk FOREIGN KEY ( booking_booking_id )
        REFERENCES booking ( booking_id );

ALTER TABLE notification
    ADD CONSTRAINT notification_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE penalty
    ADD CONSTRAINT penalty_booking_fk FOREIGN KEY ( booking_booking_id )
        REFERENCES booking ( booking_id );

ALTER TABLE penalty
    ADD CONSTRAINT penalty_staff_fk FOREIGN KEY ( staff_staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE penalty
    ADD CONSTRAINT penalty_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE report
    ADD CONSTRAINT report_users_fk FOREIGN KEY ( user_userid )
        REFERENCES users ( user_id );

ALTER TABLE room_assignment
    ADD CONSTRAINT room_assignment_room_fk FOREIGN KEY ( room_room_id )
        REFERENCES room ( room_id );

ALTER TABLE room_assignment
    ADD CONSTRAINT room_assignment_staff_fk FOREIGN KEY ( staff_staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE room_equipment
    ADD CONSTRAINT room_equipment_equipment_fk FOREIGN KEY ( equipment_equipment_id )
        REFERENCES equipment ( equipment_id );

ALTER TABLE room_equipment
    ADD CONSTRAINT room_equipment_room_fk FOREIGN KEY ( room_room_id )
        REFERENCES room ( room_id );

ALTER TABLE room
    ADD CONSTRAINT room_floor_fk FOREIGN KEY ( floor_floor_id )
        REFERENCES floor ( floor_id );

ALTER TABLE room
    ADD CONSTRAINT room_room_type_fk FOREIGN KEY ( room_type_room_type_id )
        REFERENCES room_type ( room_type_id );

ALTER TABLE staff
    ADD CONSTRAINT staff_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE users
    ADD CONSTRAINT users_affiliation_fk FOREIGN KEY ( affiliation_affiliation_id )
        REFERENCES affiliation ( affiliation_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            18
-- CREATE INDEX                             3
-- ALTER TABLE                             51
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
