import type {
  AppState,
  Booking,
  BookingStatus,
} from "../../../../packages/contracts/src/index";

const booking = (
  id: number,
  userId: number,
  roomId: number,
  day: string,
  start: string,
  end: string,
  status: BookingStatus,
  purpose: string,
): Booking => ({
  id,
  ref: `BK-2569-${String(id).padStart(4, "0")}`,
  userId,
  roomId,
  start: `${day}T${start}:00+07:00`,
  end: `${day}T${end}:00+07:00`,
  purpose,
  attendees: 4,
  participants: [],
  equipment: [],
  status,
  createdAt: "2026-10-08T08:00:00+07:00",
  ...(status === "COMPLETED"
    ? { checkedInAt: `${day}T${start}:00+07:00` }
    : {}),
});
export function createSeed(): AppState {
  return {
    schema: 1,
    now: "2026-10-08T09:10:00+07:00",
    users: [
      {
        id: 1,
        name: "ณัฐวดี ใจดี",
        email: "student.demo@kkumail.com",
        phone: "0812345678",
        affiliation: "วิทยาลัยการคอมพิวเตอร์",
        role: "USER",
        active: true,
      },
      {
        id: 2,
        name: "พิมพ์ชนก ศรีสุข",
        email: "staff.demo@kku.ac.th",
        phone: "043000000",
        affiliation: "สำนักหอสมุด",
        role: "STAFF",
        active: true,
      },
      {
        id: 3,
        name: "ผู้ดูแลระบบ",
        email: "admin.demo@kku.ac.th",
        phone: "043000001",
        affiliation: "ฝ่ายบริหารพื้นที่",
        role: "ADMIN",
        active: true,
      },
      {
        id: 4,
        name: "ธนกร เรียนดี",
        email: "member.demo@kkumail.com",
        phone: "0801234567",
        affiliation: "คณะวิศวกรรมศาสตร์",
        role: "USER",
        active: true,
      },
    ],
    buildings: [
      { id: 1, name: "สำนักหอสมุด", floors: 5 },
      { id: 2, name: "วิทยาลัยการคอมพิวเตอร์", floors: 4 },
      { id: 3, name: "อาคารเรียนรวม", floors: 3 },
    ],
    rooms: [
      {
        id: 1,
        code: "LIB-201",
        name: "ห้องศึกษากลุ่ม มอดินแดง",
        buildingId: 1,
        floor: 2,
        capacity: 8,
        type: "ห้องศึกษากลุ่ม",
        amenities: ["Wi-Fi", "กระดานไวท์บอร์ด", "จอแสดงผล"],
        status: "AVAILABLE",
        reason: "",
        scene: 0,
      },
      {
        id: 2,
        code: "LIB-302",
        name: "ห้องประชุม กัลปพฤกษ์",
        buildingId: 1,
        floor: 3,
        capacity: 16,
        type: "ห้องประชุม",
        amenities: ["Wi-Fi", "โปรเจกเตอร์", "กระดานไวท์บอร์ด"],
        status: "AVAILABLE",
        reason: "",
        scene: 1,
      },
      {
        id: 3,
        code: "CP-204",
        name: "ห้องทำงานร่วมกัน",
        buildingId: 2,
        floor: 2,
        capacity: 12,
        type: "ห้องศึกษากลุ่ม",
        amenities: ["Wi-Fi", "จอแสดงผล", "กระดานไวท์บอร์ด"],
        status: "AVAILABLE",
        reason: "",
        scene: 2,
      },
      {
        id: 4,
        code: "GE-101",
        name: "ห้องเรียนรู้ อีสาน",
        buildingId: 3,
        floor: 1,
        capacity: 40,
        type: "ห้องเรียน",
        amenities: ["Wi-Fi", "โปรเจกเตอร์", "กระดานไวท์บอร์ด"],
        status: "AVAILABLE",
        reason: "",
        scene: 3,
      },
      {
        id: 5,
        code: "LIB-401",
        name: "ห้องประชุม แก่นนคร",
        buildingId: 1,
        floor: 4,
        capacity: 24,
        type: "ห้องประชุม",
        amenities: ["Wi-Fi", "โปรเจกเตอร์", "จอแสดงผล"],
        status: "MAINTENANCE",
        reason: "ปรับปรุงระบบปรับอากาศ",
        scene: 4,
      },
      {
        id: 6,
        code: "CP-301",
        name: "ห้องไอเดียและนวัตกรรม",
        buildingId: 2,
        floor: 3,
        capacity: 6,
        type: "ห้องศึกษากลุ่ม",
        amenities: ["Wi-Fi", "กระดานไวท์บอร์ด"],
        status: "AVAILABLE",
        reason: "",
        scene: 5,
      },
    ],
    equipment: [
      { id: 1, name: "โปรเจกเตอร์พกพา", total: 4, remaining: 4 },
      { id: 2, name: "ไมโครโฟนไร้สาย", total: 6, remaining: 6 },
      { id: 3, name: "สาย HDMI", total: 10, remaining: 10 },
    ],
    bookings: [
      booking(
        1,
        1,
        1,
        "2026-10-08",
        "09:00",
        "10:00",
        "APPROVED",
        "ประชุมเตรียมโครงงาน",
      ),
      booking(
        2,
        1,
        3,
        "2026-10-09",
        "13:00",
        "15:00",
        "PENDING",
        "ออกแบบระบบงานกลุ่ม",
      ),
      booking(
        3,
        4,
        2,
        "2026-10-09",
        "10:00",
        "12:00",
        "PENDING",
        "ประชุมชมรมอาสา",
      ),
      booking(
        4,
        1,
        6,
        "2026-10-07",
        "13:00",
        "15:00",
        "COMPLETED",
        "ทบทวนบทเรียน",
      ),
      booking(
        5,
        4,
        4,
        "2026-10-06",
        "09:00",
        "11:00",
        "NO_SHOW",
        "นำเสนอโครงงาน",
      ),
      booking(6, 4, 2, "2026-10-05", "13:00", "15:00", "NO_SHOW", "ประชุมทีม"),
      booking(7, 4, 1, "2026-10-04", "10:00", "12:00", "NO_SHOW", "ทำงานกลุ่ม"),
      {
        ...booking(
          8,
          1,
          4,
          "2026-10-06",
          "13:00",
          "15:00",
          "CANCELLED",
          "เตรียมการนำเสนอ",
        ),
        reason: "ผู้จองยกเลิก",
      },
    ],
    notices: [
      {
        id: 1,
        userId: 1,
        bookingId: 1,
        subject: "คำขอได้รับการอนุมัติ",
        content:
          "ห้องศึกษากลุ่ม มอดินแดง วันที่ 8 ต.ค. 2569 เวลา 09:00–10:00 น.",
        status: "SENT",
        createdAt: "2026-10-08T08:20:00+07:00",
        attempts: 1,
      },
      {
        id: 2,
        userId: 1,
        bookingId: 2,
        subject: "ได้รับคำขอจองแล้ว",
        content: "เจ้าหน้าที่จะพิจารณาคำขอของคุณภายใน 4 ชั่วโมง",
        status: "QUEUED",
        createdAt: "2026-10-08T08:00:00+07:00",
        attempts: 0,
      },
      {
        id: 3,
        userId: 4,
        bookingId: 3,
        subject: "ได้รับคำขอจองแล้ว",
        content: "ห้องประชุม กัลปพฤกษ์ รอเจ้าหน้าที่พิจารณา",
        status: "FAILED",
        createdAt: "2026-10-08T08:00:00+07:00",
        attempts: 2,
      },
    ],
    violations: [5, 6, 7].map((id, i) => ({
      id: i + 1,
      userId: 4,
      bookingId: id,
      type: "NO_SHOW",
      at: `2026-10-0${6 - i}T09:31:00+07:00`,
    })),
    penalties: [],
    closures: [],
    inspections: [],
    messages: [],
    audit: [
      {
        id: 1,
        actorId: 2,
        at: "2026-10-08T08:20:00+07:00",
        text: "อนุมัติคำขอ BK-2569-0001",
        bookingId: 1,
      },
    ],
    holidays: ["2026-10-13"],
    assignments: [{ userId: 2, roomIds: [1, 2, 5] }],
  };
}
